### GET all models
GET {{host}}/api/models
Content-Type: application/json;charset=UTF-8

### Get text response with settings (example_1)
POST {{host}}/api/generate/text
Content-Type: application/json;charset=UTF-8

{
  "prompt": "I want to find top-10 books",
  "max_tokens": 700,
  "temperature": 1.0,
  "model": "anthropic.claude-v2-1"
}

### Get text response with default temperature (example_2)
POST {{host}}/api/generate/text
Content-Type: application/json;charset=UTF-8

{
  "prompt": "I want to find top-10 books",
  "max_tokens": 500,
  "model": "gpt-4o-2024-08-06"
}

### Get text response with default max_tokens (example_3)
POST {{host}}/api/generate/text
Content-Type: application/json;charset=UTF-8

{
  "prompt": "I want to find top-10 books",
  "temperature": 0.7,
  "model": "amazon.titan-tg1-large"
}