### Get JSON response
POST {{host}}/api/generate/json
Content-Type: application/json;charset=UTF-8

{
  "input": "I want to find top-10 books about world history",
  "max_tokens": 1000,
  "temperature": 0.5
}

### Get JSON response with history
POST {{host}}/api/generate/text/history
Content-Type: application/json;charset=UTF-8

{
  "input": "I want to find top-10 books about world history",
  "max_tokens": 1000,
  "temperature": 0.5
}